# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision_msgs/obj_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class obj_msg(genpy.Message):
  _md5sum = "9e2023751502f5af149d77b1a75f5f33"
  _type = "vision_msgs/obj_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
float64 obj_id
float64 obj_score
float64 obj_center_x
float64 obj_center_y
float64 obj_size_x
float64 obj_size_y
"""
  __slots__ = ['obj_id','obj_score','obj_center_x','obj_center_y','obj_size_x','obj_size_y']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       obj_id,obj_score,obj_center_x,obj_center_y,obj_size_x,obj_size_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(obj_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.obj_id is None:
        self.obj_id = 0.
      if self.obj_score is None:
        self.obj_score = 0.
      if self.obj_center_x is None:
        self.obj_center_x = 0.
      if self.obj_center_y is None:
        self.obj_center_y = 0.
      if self.obj_size_x is None:
        self.obj_size_x = 0.
      if self.obj_size_y is None:
        self.obj_size_y = 0.
    else:
      self.obj_id = 0.
      self.obj_score = 0.
      self.obj_center_x = 0.
      self.obj_center_y = 0.
      self.obj_size_x = 0.
      self.obj_size_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.obj_id, _x.obj_score, _x.obj_center_x, _x.obj_center_y, _x.obj_size_x, _x.obj_size_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.obj_id, _x.obj_score, _x.obj_center_x, _x.obj_center_y, _x.obj_size_x, _x.obj_size_y,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.obj_id, _x.obj_score, _x.obj_center_x, _x.obj_center_y, _x.obj_size_x, _x.obj_size_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.obj_id, _x.obj_score, _x.obj_center_x, _x.obj_center_y, _x.obj_size_x, _x.obj_size_y,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
